sonar.projectKey=jirascrap
sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.go.coverage.reportPaths=coverage.out

sonar.test.inclusions=**/*_test.go

sonar.exclusions=**/sqlcgen/**,**/*_test.go
sonar.coverage.exclusions=**/sqlcgen/**,**/cmd/**
