sonar.projectKey=codedogapp_jirascrap
sonar.organization=codedogapp
sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.go.coverage.reportPaths=coverage.out

sonar.test.inclusions=**/*_test.go

sonar.exclusions=**/sqlcdb/**,**/*_test.go,e2e/demo.gif
sonar.coverage.exclusions=**/sqlcdb/**
