// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: logs.sql

package sqlcdb

import (
	"context"
)

const insertLog = `-- name: InsertLog :exec
INSERT INTO logs (level, message) VALUES (?, ?)
`

type InsertLogParams struct {
	Level   string
	Message string
}

func (q *Queries) InsertLog(ctx context.Context, arg InsertLogParams) error {
	_, err := q.db.ExecContext(ctx, insertLog, arg.Level, arg.Message)
	return err
}
