// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

type IssueTag struct {
	ID  string
	Tag string
}

type IssueTodo struct {
	ID       int64
	TicketID string
	Title    string
	Done     int64
}

type Log struct {
	ID        int64
	Level     string
	Message   string
	CreatedAt string
}

type Ticket struct {
	ID             string
	Summary        string
	Reporter       string
	Status         string
	StatusCategory string
	Priority       string
	CreatedAt      string
	UpdatedAt      string
	Markdown       string
	Type           string
	EpicID         *string
}
