// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package sqlcdb

import (
	"context"
)

const deleteTagsByID = `-- name: DeleteTagsByID :exec
DELETE FROM issue_tags WHERE id = ?
`

func (q *Queries) DeleteTagsByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTagsByID, id)
	return err
}

const getUniqueTags = `-- name: GetUniqueTags :many
SELECT DISTINCT tag FROM issue_tags ORDER BY tag ASC
`

func (q *Queries) GetUniqueTags(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUniqueTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTag = `-- name: InsertTag :exec
INSERT INTO issue_tags (id, tag) VALUES (?, ?)
`

type InsertTagParams struct {
	ID  string
	Tag string
}

func (q *Queries) InsertTag(ctx context.Context, arg InsertTagParams) error {
	_, err := q.db.ExecContext(ctx, insertTag, arg.ID, arg.Tag)
	return err
}
