// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package sqlcdb

import (
	"context"
)

const deleteEpicChildren = `-- name: DeleteEpicChildren :exec
DELETE FROM tickets WHERE epic_id = ?
`

func (q *Queries) DeleteEpicChildren(ctx context.Context, epicID *string) error {
	_, err := q.db.ExecContext(ctx, deleteEpicChildren, epicID)
	return err
}

const deleteTopLevelTickets = `-- name: DeleteTopLevelTickets :exec
DELETE FROM tickets WHERE epic_id IS NULL
`

func (q *Queries) DeleteTopLevelTickets(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteTopLevelTickets)
	return err
}

const getAllEpicChildren = `-- name: GetAllEpicChildren :many
SELECT t.epic_id,
       t.id,
       t.summary,
       t.reporter,
       t.status,
       t.status_category,
       t.priority,
       t.type,
       t.created_at,
       t.updated_at,
       t.markdown,
       COALESCE(GROUP_CONCAT(it.tag), '') AS tags
FROM tickets t
LEFT JOIN issue_tags it ON t.id = it.id
WHERE t.epic_id IS NOT NULL
GROUP BY t.id
ORDER BY t.epic_id, t.updated_at DESC
`

type GetAllEpicChildrenRow struct {
	EpicID         *string
	ID             string
	Summary        string
	Reporter       string
	Status         string
	StatusCategory string
	Priority       string
	Type           string
	CreatedAt      string
	UpdatedAt      string
	Markdown       string
	Tags           interface{}
}

func (q *Queries) GetAllEpicChildren(ctx context.Context) ([]GetAllEpicChildrenRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllEpicChildren)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllEpicChildrenRow
	for rows.Next() {
		var i GetAllEpicChildrenRow
		if err := rows.Scan(
			&i.EpicID,
			&i.ID,
			&i.Summary,
			&i.Reporter,
			&i.Status,
			&i.StatusCategory,
			&i.Priority,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Markdown,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCachedTickets = `-- name: GetCachedTickets :many
SELECT t.id, t.summary, t.reporter, t.status, t.status_category,
       t.priority, t.type, t.created_at, t.updated_at, t.markdown,
       COALESCE(GROUP_CONCAT(it.tag), '') AS tags
FROM tickets t
LEFT JOIN issue_tags it ON t.id = it.id
WHERE t.epic_id IS NULL
   OR LOWER(t.type) = 'epic'
GROUP BY t.id
ORDER BY t.updated_at DESC
`

type GetCachedTicketsRow struct {
	ID             string
	Summary        string
	Reporter       string
	Status         string
	StatusCategory string
	Priority       string
	Type           string
	CreatedAt      string
	UpdatedAt      string
	Markdown       string
	Tags           interface{}
}

func (q *Queries) GetCachedTickets(ctx context.Context) ([]GetCachedTicketsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCachedTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCachedTicketsRow
	for rows.Next() {
		var i GetCachedTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.Summary,
			&i.Reporter,
			&i.Status,
			&i.StatusCategory,
			&i.Priority,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Markdown,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTicket = `-- name: UpsertTicket :exec
INSERT OR REPLACE INTO tickets (
  id, summary, reporter, status, status_category,
  priority, type, created_at, updated_at, markdown, epic_id
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type UpsertTicketParams struct {
	ID             string
	Summary        string
	Reporter       string
	Status         string
	StatusCategory string
	Priority       string
	Type           string
	CreatedAt      string
	UpdatedAt      string
	Markdown       string
	EpicID         *string
}

func (q *Queries) UpsertTicket(ctx context.Context, arg UpsertTicketParams) error {
	_, err := q.db.ExecContext(ctx, upsertTicket,
		arg.ID,
		arg.Summary,
		arg.Reporter,
		arg.Status,
		arg.StatusCategory,
		arg.Priority,
		arg.Type,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Markdown,
		arg.EpicID,
	)
	return err
}
