// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todos.sql

package sqlcdb

import (
	"context"
)

const deleteTodosByTicket = `-- name: DeleteTodosByTicket :exec
DELETE FROM issue_todos WHERE ticket_id = ?
`

func (q *Queries) DeleteTodosByTicket(ctx context.Context, ticketID string) error {
	_, err := q.db.ExecContext(ctx, deleteTodosByTicket, ticketID)
	return err
}

const getTodosByTicket = `-- name: GetTodosByTicket :many
SELECT id, title, done FROM issue_todos WHERE ticket_id = ? ORDER BY id ASC
`

type GetTodosByTicketRow struct {
	ID    int64
	Title string
	Done  int64
}

func (q *Queries) GetTodosByTicket(ctx context.Context, ticketID string) ([]GetTodosByTicketRow, error) {
	rows, err := q.db.QueryContext(ctx, getTodosByTicket, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTodosByTicketRow
	for rows.Next() {
		var i GetTodosByTicketRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Done); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTodo = `-- name: InsertTodo :exec
INSERT INTO issue_todos (ticket_id, title, done) VALUES (?, ?, ?)
`

type InsertTodoParams struct {
	TicketID string
	Title    string
	Done     int64
}

func (q *Queries) InsertTodo(ctx context.Context, arg InsertTodoParams) error {
	_, err := q.db.ExecContext(ctx, insertTodo, arg.TicketID, arg.Title, arg.Done)
	return err
}
